// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vtekqglogiifaljexmpv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0ZWtxZ2xvZ2lpZmFsamV4bXB2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0MjExOTYsImV4cCI6MjA2MTk5NzE5Nn0.mm-HVgA-nXDMnx_v6TWFv4Ya0dIy8T1bMO2Oe1EfwBo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);